In [ ]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\frank y cami\appdata\local\programs\python\python311\lib\site-packages (18.1.0)Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_parquet('yellow_tripdata_2022-01.parquet')
data2 = pd.read_parquet('yellow_tripdata_2022-02.parquet')
data3 = pd.read_parquet('yellow_tripdata_2022-03.parquet')
data4 = pd.read_parquet('yellow_tripdata_2022-04.parquet')
data5 = pd.read_parquet('yellow_tripdata_2022-05.parquet')
data6 = pd.read_parquet('yellow_tripdata_2022-06.parquet')
data7 = pd.read_parquet('yellow_tripdata_2022-07.parquet')
data8 = pd.read_parquet('yellow_tripdata_2022-08.parquet')
data9 = pd.read_parquet('yellow_tripdata_2022-09.parquet')
data10 = pd.read_parquet('yellow_tripdata_2022-10.parquet')
data11 = pd.read_parquet('yellow_tripdata_2022-11.parquet')
data12 = pd.read_parquet('yellow_tripdata_2022-12.parquet')
data13 = pd.read_parquet('yellow_tripdata_2023-01.parquet')
data14 = pd.read_parquet('yellow_tripdata_2023-02.parquet')
data15 = pd.read_parquet('yellow_tripdata_2023-03.parquet')
data16 = pd.read_parquet('yellow_tripdata_2023-04.parquet')
data17 = pd.read_parquet('yellow_tripdata_2023-05.parquet')
data18 = pd.read_parquet('yellow_tripdata_2023-06.parquet')
data19 = pd.read_parquet('yellow_tripdata_2023-07.parquet')
data20 = pd.read_parquet('yellow_tripdata_2023-08.parquet')
data21 = pd.read_parquet('yellow_tripdata_2023-09.parquet')
data22 = pd.read_parquet('yellow_tripdata_2023-10.parquet')
data23 = pd.read_parquet('yellow_tripdata_2023-11.parquet')
data24 = pd.read_parquet('yellow_tripdata_2023-12.parquet')
data25 = pd.read_parquet('yellow_tripdata_2024-01.parquet')
data26 = pd.read_parquet('yellow_tripdata_2024-02.parquet')
data27 = pd.read_parquet('yellow_tripdata_2024-03.parquet')
data28 = pd.read_parquet('yellow_tripdata_2024-04.parquet')
data29 = pd.read_parquet('yellow_tripdata_2024-05.parquet')
data30 = pd.read_parquet('yellow_tripdata_2024-06.parquet')
data31 = pd.read_parquet('yellow_tripdata_2024-07.parquet')
data32 = pd.read_parquet('yellow_tripdata_2024-08.parquet')
data33 = pd.read_parquet('yellow_tripdata_2024-09.parquet')

In [ ]:
datas =[data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,
        data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,data31,data32,data33]

In [ ]:
columnas_sel =['passenger_count','trip_distance','payment_type','day_pickup','hour_pickup','year','mes','duracion del viaje','tarifa - peajes']

In [ ]:
i=1
for data in datas:



    # garantizar que la columna este en formato datetime
    data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])


    # Crear la columna para el día
    data['day_pickup'] = data['tpep_pickup_datetime'].dt.day

    # Crear la columna para la hora
    data['hour_pickup'] = data['tpep_pickup_datetime'].dt.hour

    # Crear la columna para el ano
    data['year'] = data['tpep_pickup_datetime'].dt.year

    # Crear la columna para el mes
    data['mes'] = data['tpep_pickup_datetime'].dt.month

    # Crear la columna duracion de viaje

    data['duracion del viaje'] = data['tpep_dropoff_datetime'] -  data['tpep_pickup_datetime']

    # Convertir la columna 'duracion del viaje' a formato timedelta
    data['duracion del viaje'] = pd.to_timedelta(data['duracion del viaje'])

    # Convertir la duración a minutos totales
    data['duracion del viaje'] = data['duracion del viaje'].dt.total_seconds() / 60

    # Crear columna tarifa - peaje

    data['tarifa - peajes']= data['total_amount'] -  data['tolls_amount']

    # Tomar el 20% del dataset como muestra
    datas[i-1] = data.sample(frac=0.2, random_state=42)

    print(f'data{i} iterada')
    i=i+1

data1 iterada
data2 iterada
data3 iterada
data4 iterada
data5 iterada
data6 iterada
data7 iterada
data8 iterada
data9 iterada
data10 iterada
data11 iterada
data12 iterada
data13 iterada
data14 iterada
data15 iterada
data16 iterada
data17 iterada
data18 iterada
data19 iterada
data20 iterada
data21 iterada
data22 iterada
data23 iterada
data24 iterada
data25 iterada
data26 iterada
data27 iterada
data28 iterada
data29 iterada
data30 iterada
data31 iterada
data32 iterada
data33 iterada

In [ ]:
datas[0].shape

NameError: name 'datas' is not defined

In [ ]:
for i in range(len(datas)):
    datas[i] = datas[i][columnas_sel]
    print(f'columna definida en data{i+1}')

columna definida en data1
columna definida en data2
columna definida en data3
columna definida en data4
columna definida en data5
columna definida en data6
columna definida en data7
columna definida en data8
columna definida en data9
columna definida en data10
columna definida en data11
columna definida en data12
columna definida en data13
columna definida en data14
columna definida en data15
columna definida en data16
columna definida en data17
columna definida en data18
columna definida en data19
columna definida en data20
columna definida en data21
columna definida en data22
columna definida en data23
columna definida en data24
columna definida en data25
columna definida en data26
columna definida en data27
columna definida en data28
columna definida en data29
columna definida en data30
columna definida en data31
columna definida en data32
columna definida en data33

In [ ]:
data1,data2,data3,data4,data5,data6,data7 = datas[:7]

data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,data31,data32,data33= datas[7:]

In [ ]:
# Verificamos que los datasets tengan las mismas columnas
if list(data1.columns) == list(data2.columns) == list(data3.columns)==list(data4.columns)==list(data5.columns)==list(data16.columns)==list(data7.columns)==list(data8.columns)==list(data9.columns)==list(data10
.columns)==list(data11.columns)==list(data12.columns)==list(data13.columns)==list(data14.columns)==list(data15.columns)==list(data16.columns)==list(data17.columns)==list(data18.columns)==list(data19.columns)==list(data20.columns)==list(data21.columns)==list(data22
.columns)==list(data23.columns)==list(data24.columns)==list(data25.columns)==list(data26.columns)==list(data27.columns)==list(data28.columns)==list(data29.columns)==list(data30.columns)==list(data31.columns)==list(data32.columns)==list(data33.columns):
    # Unifica los datasets
    viajes_taxis_y= pd.concat([data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,data31,data32,data33], ignore_index=True)
    print("Datasets unificados con éxito.")
else:
    print("Los datasets no tienen las mismas columnas y no se pueden unificar.")

Datasets unificados con éxito.

In [ ]:
# Guarda el dataset unificado en un nuevo archivo parquet
viajes_taxis_y.to_parquet("viajes_taxis_y.parquet", engine = 'pyarrow',index=False)

In [ ]:
viajes_taxis_y.head(3)

,passenger_count,trip_distance,payment_type,day_pickup,hour_pickup,year,mes,duracion del viaje,tarifa - peajes
0,2.0,1.50,1,15,0,2022,1,8.733333,14.16
1,1.0,2.60,1,13,17,2022,1,12.616667,16.30
2,1.0,3.73,1,19,18,2022,1,14.833333,21.36

In [ ]:
viajes_taxis_y.shape

(21597507, 9)